<?php

function buildpopdsheet($thedate, $timeslotgen)

{

	require ("collection.php");

	require ("startdb.php");



	$collection = new Collection();

	

	$morning = new Collection();

	$noon = new Collection();

	$evening = new Collection();

	

	

	function checkforlabtest($row,$thedate)

	{

		$thelabtest=$row['LABTEST'];

		if ($row['LABTEST']=="")

		return 0;

		$query='select AUTOTAG FROM wo WHERE AUTOTAG="'.$row['ADDITIONID'].'"';

		$result=mysql_query($query);

		if (mysql_num_rows($result)>0)

		return 1;

		

		$query='select * from fermprot where ID="'.$row['FERMPROTID'].'"';

		$result=mysql_query($query);

		$fp=mysql_fetch_array($result);

		

		$query='insert into wo SET AUTOTAG="'.$row['ADDITIONID'].'",

         TYPE="LAB TEST",

         LOT="'.$fp['LOT'].'",

         DUEDATE="'.$thedate.'",

         ENDDATE="'.$thedate.'",

         VESSELTYPE="'.$fp['VESSELTYPE'].'",

         VESSELID="'.$fp['VESSELID'].'",

         AUTOGENERATED="YES",

         WORKPERFORMEDBY="CCC",

         STATUS="ASSIGNED",

         DELETED=0';

		mysql_query($query);

		$woid=mysql_insert_id();

		$query='insert into labtest SET WOID="'.$woid.'"';

		mysql_query($query);

		$labid=mysql_insert_id();

		$query='insert into labresults SET LABTESTID="'.$labid.'",

            LABTEST="'.$thelabtest.'"';

		//        echo $query;

		mysql_query($query);

		return 1;

		

	}

	

	function pr($therow)

	{

		echo $therow[id] . ", ". $therow['LOT'].", ".$therow['DATE'].", ".$therow['vessel'].", ".$therow['vesseltype'].

		", CB-".$therow['BRIX'].", SB-".$therow['POSTARTBRIX'].", EB-".$therow['POENDBRIX']. ", ". $therow['temp']."<br>";

	}

	

	function pc($thecollection)

	{

		echo "-----------------".$thecollection->count()."----------------<br>";

		$thecollection->first();

		while (!$thecollection->lastitem())

		{

			$cur = $thecollection->current();

			pr($cur);

			$thecollection->nextitem();

		}

		echo "---------------------------------<br>";

	}

	

	function pc2($thecollection)

	{

		$thecollection->first();

		while (!$thecollection->lastitem())

		{

			$val = $thecollection->current();

			pr($val['Row']);

			echo "---" . $val['Activity']."<br>";

			$thecollection->nextitem();

		}

	}

	

	function isyes ($value)

	{

		if ($value == "Yes" | $value == "YES")

		{

			return true;

		}

		return false;

	}

	

	function blankout($isyes,$value)

	{

		if ($isyes == "Yes" | $isyes == "YES")

		return $value;

		else

		return "";

	}

	

	

	function isnotin($thecollection, $therow)

	{

		$thecollection->first();

		$currentrow = $thecollection->current();

		if (($currentrow['LOT']== $therow['LOT'])&

		($currentrow['vessel'] == $therow['vessel']))

		{

			return false;

		}

		while ($thecollection->hasNext())

		{

			$currentrow = $thecollection->next();

			if (($currentrow['LOT']== $therow['LOT'])&

			($currentrow['vessel'] == $therow['vessel']))

			{

				return false;

			}

		}

		return true;

	}

	

	function setbrix($theval)

	{

		if ($theval=="")

			return 29;

        else

            return $theval;

            

	}

	

	function withinrange($theval, $start, $end)

	{

		if ($theval=="")

		{

			//        echo "encountered null";

			//         echo $theval.'-'.$start.'-'.$end.'<br>';

			//        exit;

			$theval=29;

		}

		//     echo $theval.'-'.$start.'-'.$end.'<br>';

		//      if ($theval == "")

		//         return true;

		if (($theval <= $start) & ($theval > $end))

		{

			//            echo 'true<br>';

			return true;

		}

		

		//       echo 'false<br>';

		return false;

	}

	

	function addwo(&$thecollection,$activity,$therow, $brix)

	{

		//echo 'added to '.$activity.'  '.$therow['timeslot'].'<br>';

		$wo=array('Activity'=>$activity, 'Row'=>$therow, 'brix'=>setbrix($brix));

		$thecollection->add($wo);

		

	}



	function stdur($type,$duration_strength)

		{

			if ($type=="PUNCH DOWN")

			  return 'STRENGTH="'.$duration_strength.'", ';

			else

			  return 'DURATION="'.$duration_strength.'", ';

		}

		

	function updatewo($type, $lot, $thedate, $cc, $vesseltype, $vesselid, $timeslot, $strength, $duration_strength)

	{

		

        if (($type=="PUNCH DOWN")&($duration_strength=="NONE"))

        {

            return;

        }

          

       	$query2='select wo.ID from wo WHERE LOT="'.$lot.'" AND TIMESLOT="'.$timeslot.'" AND DUEDATE="'.$thedate.'" AND VESSELTYPE="'.$vesseltype.'" AND VESSELID="'.$vesselid.'"';



       	$result2=mysql_query($query2);

       	if (mysql_num_rows($result2)>0)

       	{       

       		$therow=mysql_fetch_array($result2);

       		$thequery='UPDATE wo SET TYPE="'.$type.'",

        				LOT="'.$lot.'",

         				DUEDATE="'.$thedate.'",

         				ENDDATE="'.$thedate.'",

         				CLIENTCODE="'.$cc . '",

         				VESSELTYPE="'.$vesseltype. '",

			         	VESSELID="'.$vesselid.'",'.stdur($type,$duration_strength).'

			            AUTOGENERATED="YES",

         				WORKPERFORMEDBY="CCC",

         				STATUS="ASSIGNED",

         				DELETED=0,

         				TIMESLOT="'.$timeslot.'" WHERE (wo.ID="'.$therow['ID'].'") limit 1';

       	}

       	else

       	{

       		$thequery='INSERT INTO wo SET TYPE="'.$type.'",

        				LOT="'.$lot.'",

         				DUEDATE="'.$thedate.'",

         				ENDDATE="'.$thedate.'",

         				CLIENTCODE="'.$cc . '",

         				VESSELTYPE="'.$vesseltype. '",

			         	VESSELID="'.$vesselid.'",'.stdur($type,$duration_strength).'

			            AUTOGENERATED="YES",

         				WORKPERFORMEDBY="CCC",

         				STATUS="ASSIGNED",

         				DELETED=0,

         				TIMESLOT="'.$timeslot.'"';

       	}



       	//echo $thequery.'<br>';



		$result2=mysql_query($thequery);

	}

	

	$query = "SELECT 

	  fermprot.ID,

      `fermprot`.`POPM`,

 	 `fermprot`.`PONOON`,

  	`fermprot`.`POAM`,

  	`fermprot`.`PDPM`,

  	`fermprot`.`PDNOON`,

  	`fermprot`.`PDAM`,

  	`fermprot`.`LOT`,

  	`fermprot`.`VESSELTYPE`,

  	`fermprot`.`VESSELID`,

  	`fermprot`.`STATUS`

	FROM

  		`fermprot`

	WHERE

  		(`fermprot`.`STATUS` = \"ACTIVE\")";

	

//	echo $query;

//	exit;



	$result = mysql_query($query);

	$num_results = mysql_num_rows($result);



	for ($i=0; $i <$num_results; $i++)

	{

		$row = mysql_fetch_array($result);

		$cc=explode('-',$row['LOT']);



        if ($row['POAM']>0)

        	updatewo("PUMP OVER",$row['LOT'],$thedate, $cc[1], $row['VESSELTYPE'], $row['VESSELID'], "MORNING", "", $row['POAM']);

        if ($row['PONOON']>0)

        	updatewo("PUMP OVER",$row['LOT'],$thedate, $cc[1], $row['VESSELTYPE'], $row['VESSELID'], "NOON", "", $row['PONOON']);         

        if ($row['POPM']>0)

        	updatewo("PUMP OVER",$row['LOT'],$thedate, $cc[1], $row['VESSELTYPE'], $row['VESSELID'], "EVENING", "", $row['POPM']);                   

        if ($row['PDAM']!="")

        	updatewo("PUNCH DOWN",$row['LOT'],$thedate, $cc[1], $row['VESSELTYPE'], $row['VESSELID'], "MORNING", "", $row['PDAM']);                            

        if ($row['PDNOON']!="")

        	updatewo("PUNCH DOWN",$row['LOT'],$thedate, $cc[1], $row['VESSELTYPE'], $row['VESSELID'], "NOON", "", $row['PDNOON']);                                      

        if ($row['PDPM']!="")

        	updatewo("PUNCH DOWN",$row['LOT'],$thedate, $cc[1], $row['VESSELTYPE'], $row['VESSELID'], "EVENING", "", $row['PDPM']);                            



	}

}

