<?php

function buildpopdsheet($thedate, $timeslotgen)

{

	require ("collection.php");

	require ("startdb.php");

	//  echo $thedate;

	

	$collection = new Collection();

	

	$morning = new Collection();

	$noon = new Collection();

	$evening = new Collection();

	

	echo "hello world..."; exit;

	

	

	function checkforlabtest($row,$thedate)

	{

		$thelabtest=$row['LABTEST'];

		if ($row['LABTEST']=="")

		return 0;

		$query='select AUTOTAG FROM wo WHERE AUTOTAG="'.$row['ADDITIONID'].'"';

		$result=mysql_query($query);

		if (mysql_num_rows($result)>0)

		return 1;

		

		$query='select * from fermprot where ID="'.$row['FERMPROTID'].'"';

		$result=mysql_query($query);

		$fp=mysql_fetch_array($result);

		

		$query='insert into wo SET AUTOTAG="'.$row['ADDITIONID'].'",

         TYPE="LAB TEST",

         LOT="'.$fp['LOT'].'",

         DUEDATE="'.$thedate.'",

         ENDDATE="'.$thedate.'",

         VESSELTYPE="'.$fp['VESSELTYPE'].'",

         VESSELID="'.$fp['VESSELID'].'",

         AUTOGENERATED="YES",

         WORKPERFORMEDBY="CCC",

         STATUS="ASSIGNED",

         DELETED=0';

		mysql_query($query);

		$woid=mysql_insert_id();

		$query='insert into labtest SET WOID="'.$woid.'"';

		mysql_query($query);

		$labid=mysql_insert_id();

		$query='insert into labresults SET LABTESTID="'.$labid.'",

            LABTEST="'.$thelabtest.'"';

		//        echo $query;

		mysql_query($query);

		return 1;

		

	}

	

	function pr($therow)

	{

		echo $therow[id] . ", ". $therow['LOT'].", ".$therow['DATE'].", ".$therow['vessel'].", ".$therow['vesseltype'].

		", CB-".$therow['BRIX'].", SB-".$therow['POSTARTBRIX'].", EB-".$therow['POENDBRIX']. ", ". $therow['temp']."<br>";

	}

	

	function pc($thecollection)

	{

		echo "-----------------".$thecollection->count()."----------------<br>";

		$thecollection->first();

		while (!$thecollection->lastitem())

		{

			$cur = $thecollection->current();

			pr($cur);

			$thecollection->nextitem();

		}

		echo "---------------------------------<br>";

	}

	

	function pc2($thecollection)

	{

		$thecollection->first();

		while (!$thecollection->lastitem())

		{

			$val = $thecollection->current();

			pr($val['Row']);

			echo "---" . $val['Activity']."<br>";

			$thecollection->nextitem();

		}

	}

	

	function isyes ($value)

	{

		if ($value == "Yes" | $value == "YES")

		{

			return true;

		}

		return false;

	}

	

	function blankout($isyes,$value)

	{

		if ($isyes == "Yes" | $isyes == "YES")

		return $value;

		else

		return "";

	}

	

	

	function isnotin($thecollection, $therow)

	{

		$thecollection->first();

		$currentrow = $thecollection->current();

		if (($currentrow['LOT']== $therow['LOT'])&

		($currentrow['vessel'] == $therow['vessel']))

		{

			return false;

		}

		while ($thecollection->hasNext())

		{

			$currentrow = $thecollection->next();

			if (($currentrow['LOT']== $therow['LOT'])&

			($currentrow['vessel'] == $therow['vessel']))

			{

				return false;

			}

		}

		return true;

	}

	

	function setbrix($theval)

	{

		if ($theval=="")

			return 29;

        else

            return $theval;

            

	}

	

	function withinrange($theval, $start, $end)

	{

		if ($theval=="")

		{

			//        echo "encountered null";

			//         echo $theval.'-'.$start.'-'.$end.'<br>';

			//        exit;

			$theval=29;

		}

		//     echo $theval.'-'.$start.'-'.$end.'<br>';

		//      if ($theval == "")

		//         return true;

		if (($theval <= $start) & ($theval > $end))

		{

			//            echo 'true<br>';

			return true;

		}

		

		//       echo 'false<br>';

		return false;

	}

	

	function addwo(&$thecollection,$activity,$therow, $brix)

	{

		//   echo 'added to '.$activity.'  '.$therow['timeslot'].'<br>';

		$wo=array('Activity'=>$activity, 'Row'=>$therow, 'brix'=>setbrix($brix));

		$thecollection->add($wo);

		

	}

	

	function addwo2db($timeslot,$thecollection, $thedate)

	{

		

		//echo $timeslot . '--'.$thecollection->count();

		

		$therow = $thecollection->first();

		

		

		while (!$thecollection->lastitem())

		{

			$collectionitem = $thecollection->current();

			$therow = $collectionitem['Row'];

			//            echo '<pre>';

			//            print_r($therow);

			//           $query='SELECT * from fpaddmap WHERE (fpaddmap.FERMPROTID="'.$therow['id1'].'" AND

			//                                        fpaddmap.DATE="'.$thedate.'")';

			

			$datefruitarrival=firstday($therow['lot']);

			$query='SELECT * from fpaddmap left outer join additions on (fpaddmap.ADDITIONID=additions.ID) WHERE (fpaddmap.FERMPROTID="'.$therow['id1'].'")';

			$result=mysql_query($query);

			if(mysql_num_rows($result)>0)

			{

				//                echo $query.'<br>';

				

				for ($i=0; $i<mysql_num_rows($result);$i++)

				{

					$row=mysql_fetch_array($result);

					$hasadditions="";

					if (($row['DAYCOUNT']>0)&(strtotime(date("m-d-Y",strtotime($thedate)))>=strtotime(date("m-d-Y",($datefruitarrival+$row['DAYCOUNT']*86400)))))

					{

						//                      echo $query.'<br>';

						//                      echo 'day count made... '.$therow['lot'].' '.$row['DAYCOUNT'].'<br>';

						$labtest=checkforlabtest($row,date("Y-m-d",strtotime($thedate)));

						if ($labtest==0)

						{

							$frow=$row;

							$hasadditions=$frow['FERMPROTID'];

						}

					}

					else

					{

						$query='select * from fermprot where ID="'.$row['FERMPROTID'].'"';

						$result=mysql_query($query);

						$fp=mysql_fetch_array($result);

						$qbrix='select * from brixtemp where lot="'.$fp['LOT'].'" and vessel="'.$fp['VESSELID'].'" and vesseltype="'.$fp['VESSELTYPE'].'" order by DATE DESC';

						

						$qresult=mysql_query($qbrix);

						$qrow=mysql_fetch_array($qresult);

						//                                     echo $fp['LOT'].' '.$qrow['BRIX'].' <= '.$row['BRIX'].'<br>';

						if ($qrow['BRIX']<=$row['BRIX'])

						{

							//                      echo $query.'<br>';

							//                      echo 'brix made ... '.$therow['lot'].' '.$row['BRIX'].' '.$qrow['BRIX'].'<br>';

							$labtest=checkforlabtest($row,date("Y-m-d",strtotime($thedate)));

							if ($labtest==0)

							{

								//                echo 'adding addition based on brix';

								

								$frow=$row;

								$hasadditions=$frow['FERMPROTID'];

							}

						}

					}

				}

			}

			else

			$hasadditions="";

			

			$activity = $collectionitem['Activity'];

			$brix=$collectionitem['brix'];

			$lot = '"'.$therow['THELOT'].'"';

			$vessel = '"'.$therow['THEVESSELID'].'"';

			$vesseltype = '"'.$therow['THEVESSELTYPE'].'"';

	//		      echo "adding to wodb ...".$lot.' '.$vessel.' '.$vesseltype.' '.$activity.'<br>';

			if ($activity == "PD")

			{

				//       echo 'pd';

				$thetype = '"PUNCH DOWN"';

				$strength = '"'.$therow['PDSTRENGTH'].'"';

				$duration = 0;

			}

			elseif ($activity == "PD2")

			{

				//        echo 'pd2';

				$thetype = '"PUNCH DOWN"';

				$strength = '"'.$therow['PDSTRENGTH2'].'"';

				$duration = 0;

			}

			elseif ($activity == "PO2")

			{

				//        echo 'po';

				$thetype = '"PUMP OVER"';

				$strength = '"LIGHT"';

				$duration = $therow['PODURATION2'];

			}

			elseif ($activity == "PO")

			{

				//        echo 'po';

				$thetype = '"PUMP OVER"';

				$strength = '"LIGHT"';

				$duration = $therow['PODURATION'];

			}

			elseif ($activity == "DRYICE")

			{

				//        echo 'adding dry ice only...';

				$thetype = '"DRYICE"';

				$strength = '"LIGHT"';

				$duration = '"10"';

			}

			$query = 'SELECT * FROM wo WHERE (LOT='.$lot.' AND DUEDATE="'.$thedate.'" AND  VESSELTYPE='.$vesseltype.' AND

             DELETED="0" AND

             AUTOGENERATED="YES" AND

             VESSELID='.$vessel.' AND

             TYPE='.$thetype.' AND

             TIMESLOT="'.$timeslot.'")';

//			echo $query.'<br>';

			$result = mysql_query($query);

			$num_results = mysql_num_rows($result);

			//     echo $num_results;

			

			if ($num_results == 0) {

				

				$query = 'SELECT * FROM wo WHERE (LOT='.$lot.' AND DUEDATE="'.$thedate.'" AND  VESSELTYPE='.$vesseltype.' AND

             DELETED="0" AND

             VESSELID='.$vessel.' AND

             TYPE='.$thetype.' AND

             TIMESLOT="'.$timeslot.'")';

//				echo $query.'<br>';

				$result = mysql_query($query);

				$cc=explode('-',$lot);

				if (mysql_num_rows($result)==0)

				{

					$insertquery = 'INSERT INTO wo SET TYPE='.$thetype.',

         LOT='.$lot.',

         DUEDATE="'.$thedate.'",

         ENDDATE="'.$thedate.'",

         CLIENTCODE="'.$cc[1] . '",

         VESSELTYPE='.$vesseltype . ',

         VESSELID='.$vessel.',

         STRENGTH='.$strength.',

         BRIX="'.$brix.'",

         DURATION='.$duration.',

         RELATEDADDITIONSID="'.$hasadditions.'",

         AUTOGENERATED="YES",

         WORKPERFORMEDBY="CCC",

	 ALERT="'.genalert($lot,$vesseltype,$vessel).'",

         STATUS="ASSIGNED",

         DELETED=0,

         TIMESLOT="'.$timeslot.'",

         ASSIGNEDTO="SHANE"';

		//			              echo $insertquery . '<br>';

					

				}

			}

			else

			{

				$row = mysql_fetch_array($result);

				$cc=explode('-',$lot);

				

				$insertquery = 'UPDATE wo SET TYPE='.$thetype.',

         LOT='.$lot.',

         DUEDATE="'.$thedate.'",

         ENDDATE="'.$thedate.'",

         VESSELTYPE='.$vesseltype . ',

         VESSELID='.$vessel.',

          CLIENTCODE="'.$cc[1] . '",

        STRENGTH='.$strength.',

         BRIX="'.$brix.'",

         DURATION='.$duration.',

         AUTOGENERATED="YES",

         WORKPERFORMEDBY="CCC",

         RELATEDADDITIONSID="'.$hasadditions.'",

	 ALERT="'.genalert($lot,$vesseltype,$vessel).'",

         STATUS="'.$row['STATUS'].'",

         DELETED="0",

         TIMESLOT="'.$timeslot.'",

         ASSIGNEDTO="SHANE"

         WHERE (wo.ID="'.$row['ID'].'")';

				

				

			}

		//	echo $insertquery.'<br>';

			$result = mysql_query($insertquery);

			

			//      else

			//      { echo "already in ..."; }

			

			$thecollection->nextitem();

		}

	}

	

	$query = 'SELECT distinct

  MAX(`brixtemp`.`DATE`) AS `FIELD_1`,

  `brixtemp`.`lot`,

  `brixtemp`.`vesseltype`,

  `brixtemp`.`vessel`,

   fermprot.VESSELTYPE as THEVESSELTYPE,

   fermprot.VESSELID AS THEVESSELID,

  `brixtemp`.`id`,

  `brixtemp`.`BRIX`,

  `brixtemp`.`temp`,

  `fermprot`.`id` AS `id1`,

  `fermprot`.`LOT` AS THELOT,

  `fermprot`.`DATE`,

  `fermprot`.`PO`,

  `fermprot`.`PO2`,

  `fermprot`.`PD`,

  `fermprot`.`PODURATION`,

  `fermprot`.`PODURATION2`,

  `fermprot`.`POSTARTBRIX`,

  `fermprot`.`POENDBRIX`,

  `fermprot`.`PDFREQ`,

  `fermprot`.`TIMESLOT1`,

  `fermprot`.`TIMESLOT2`,

  `fermprot`.`TIMESLOT3`,

  `fermprot`.`PDSTARTBRIX`,

  `fermprot`.`PDSTRENGTH`,

  `fermprot`.`STATUS`,

  `fermprot`.`PDENDBRIX`,

  `fermprot`.`POSTARTBRIX2`,

  `fermprot`.`POENDBRIX2`,

  `fermprot`.`PDSTARTBRIX2`,

  `fermprot`.`PDENDBRIX2`,

  `fermprot`.`PDFREQ2`,

  `fermprot`.`POTIMESLOT2`,

  `fermprot`.`POFREQ2`,

  `fermprot`.`PDSTRENGTH2`,

  `fermprot`.`CLIENTCODE`,

  `fermprot`.`POFREQ`,

  `fermprot`.`PD2`,

  `fermprot`.`VESSELTYPE`,

  `fermprot`.`PDAM`,

  `fermprot`.`PDNOON`,

  `fermprot`.`PDPM`,

  `fermprot`.`POAM`,

  `fermprot`.`PONOON`,

  `fermprot`.`POPM`,

  `fermprot`.`VESSELID`

FROM

  `fermprot`

  LEFT OUTER JOIN `brixtemp` ON (`fermprot`.`LOT` = `brixtemp`.`lot` and

  `brixtemp`.`vessel` = `fermprot`.`VESSELID` AND

   `brixtemp`.`vesseltype` = `fermprot`.`VESSELTYPE`)

WHERE

  (fermprot.STATUS = "ACTIVE" and fermprot.LOT!="---")

GROUP BY

  `brixtemp`.`lot`,

  `brixtemp`.`vesseltype`,

  `brixtemp`.`vessel`,

  `brixtemp`.`id`,

  `brixtemp`.`BRIX`,

  `brixtemp`.`temp`,

  `fermprot`.`id`,

  `fermprot`.`DATE`,

  `fermprot`.`PO`,

  `fermprot`.`PD`,

  `fermprot`.`PODURATION`,

  `fermprot`.`POSTARTBRIX`,

  `fermprot`.`POENDBRIX`,

  `fermprot`.`PDFREQ`,

  `fermprot`.`PDSTARTBRIX`,

  `fermprot`.`PDSTRENGTH`,

  `fermprot`.`STATUS`,

  `fermprot`.`PDENDBRIX`,

  `fermprot`.`PDSTARTBRIX2`,

  `fermprot`.`PDENDBRIX2`,

  `fermprot`.`PDFREQ2`,

  `fermprot`.`PDSTRENGTH2`,

  `fermprot`.`CLIENTCODE`,

  `fermprot`.`POFREQ`,

  `fermprot`.`PD2`,

  `fermprot`.`VESSELTYPE`,

  `fermprot`.`VESSELID`

ORDER BY

  `FIELD_1` DESC,

  `brixtemp`.`lot`,

  `brixtemp`.`vesseltype`,

  `brixtemp`.`vessel`';

	

	    echo $query;

	      exit;

	

	$maxbrixtemp = new collection();

	

	//  echo $query;

	$result = mysql_query($query);

	$num_results = mysql_num_rows($result);

	

	for ($i=0; $i <$num_results; $i++)

	{

		$row = mysql_fetch_array($result);

		$a=$row['THELOT'];

		$b=$row['THEVESSELTYPE'];

		$c=$row['THEVESSELID'];

		

		if ($keep[$a][$b][$c]!="keep")

		{

			$keep[$a][$b][$c]="keep";

			

			if (!$maxbrixtemp->contains(array($row['THELOT'],$row['THEVESSELID'],$row['THEVESSELTYPE'],$row['TIMESLOT1'],$row['TIMESLOT2'],$row['TIMESLOT3'],$row['POTIMESLOT2'])))

			{

				$maxbrixtemp->add(array($row['THELOT'],$row['THEVESSELID'],$row['THEVESSELTYPE'],$row['TIMESLOT1'],$row['TIMESLOT2'],$row['TIMESLOT3'],$row['POTIMESLOT2']));

				$collection->add($row);

		//		       echo '     added... '.$row['THELOT'].'  '.$row['VESSELTYPE'].'  '.$row['VESSELID'].'  '.$row['TIMESLOT1'].'<BR>';

			}

		}

	}

	

	$collection->first();

	

	while (!$collection->atEnd())

	{

		$row = $collection->current();

		$ccode=$row['CLIENTCODE'];

		$lot=$row['THELOT'];

		$recid=$row['id'];

		$poyesno=$row['PO'];

		$poyesno2=$row['PO2'];

		$pdyesno=$row['PD'];

		$pdyesno2=$row['PD2'];

		$pofreq=$row['POFREQ'];

		$postartbrix=$row['POSTARTBRIX'];

		$poduration=$row['PODURATION'];

		$poendbrix=$row['POENDBRIX'];

		$pofreq2=$row['POFREQ2'];

		$postartbrix2=$row['POSTARTBRIX2'];

		$poduration2=$row['PODURATION2'];

		$poendbrix2=$row['POENDBRIX2'];

		$pdstartbrix=$row['PDSTARTBRIX'];

		$pdendbrix=$row['PDENDBRIX'];

		$pdfreq=$row['PDFREQ'];

		$pdstrength=$row['PDSTRENGTH'];

		$pdstartbrix2=$row['PDSTARTBRIX2'];

		$timeslot1=$row['TIMESLOT1'];

		$timeslot3=$row['TIMESLOT3'];

		$timeslot2=$row['TIMESLOT2'];

		$potimeslot2=$row['POTIMESLOT2'];

		$pdendbrix2=$row['PDENDBRIX2'];

		$pdfreq2=$row['PDFREQ2'];

		$pdstrength2=$row['PDSTRENGTH2'];

		$date=$row['DATE'];

		$vessel=$row['THEVESSELID'];

		$vesseltype=$row['THEVESSELTYPE'];

		$brix=$row['BRIX'];

		$temp=$row['temp'];

		$added=0;  //records whether anything gets scheduled for this lot



//		echo 'checking... '.$row['THELOT'].'  '.$row['VESSELTYPE'].'  '.$row['VESSELID'].'  '.$row['TIMESLOT1'].'<BR>';

		

		if (isyes($poyesno) & withinrange($brix,$postartbrix,$poendbrix))

		{

			//             echo $lot.'//'.$poyesno.'//'.$brix.'//'.$postartbrix.'//'.$poendbrix.'<br>';

			$added=1;

			//                     echo 'adding po'.$pofreq.'<br>';

			if ($pofreq == 1)

			{

				switch($timeslot1)

				{

					case "MORNING": addwo($morning,"PO",$row,$brix); break;

					case "NOON": addwo($noon,"PO",$row,$brix); break;

					case "EVENING": addwo($evening,"PO",$row,$brix); break;

					default: addwo($morning,"PO",$row,$brix);

				}

			}

			elseif ($pofreq == 2)

			{

				switch($timeslot1)

				{

					case "MORNING": 

					  { 

					  	addwo($morning,"PO",$row,$brix);

					  	addwo($evening,"PO",$row,$brix);

					  	break;

					  }

					case "NOON": 

					  { 

					  	addwo($noon,"PO",$row,$brix);

					  	addwo($evening,"PO",$row,$brix);

					  	break;

					  }

					case "EVENING": 

					  { 

					  	addwo($evening,"PO",$row,$brix);

					  	break;

					  }

				}

			}

			elseif ($pofreq > 2)

			{

				addwo($morning,"PO",$row,$brix);

				addwo($noon,"PO",$row,$brix);

				addwo($evening,"PO",$row,$brix);

			}

		}

		

		    //  echo 'checking '.$lot.'-'.$vesseltype.'-'.$vessel.'-'.$poyesno2.'-'.$brix.'-'.$postartbrix2.'-'.$poendbrix2.'<br>';

		if (isyes($poyesno2) & withinrange($brix,$postartbrix2,$poendbrix2))

		{

			$added=1;

			

			 //         echo 'adding po2 with freq '.$pofreq2.'<br><pre>';

			//          print_r($row);

			if ($pofreq2 == 1)

			{

				switch($potimeslot2)

				{

					case "MORNING": addwo($morning,"PO2",$row,$brix); break;

					case "NOON": addwo($noon,"PO2",$row,$brix); break;

					case "EVENING": addwo($evening,"PO2",$row,$brix); break;

					default: addwo($morning,"PO2",$row,$brix);

				}

			}

			elseif ($pofreq2 == 2)

			{

				switch($potimeslot2)

				{

					case "MORNING": 

					  { 

					  	addwo($morning,"PO2",$row,$brix);

					  	addwo($evening,"PO2",$row,$brix);

					  	break;

					  }

					case "NOON": 

					  { 

					  	addwo($noon,"PO2",$row,$brix);

					  	addwo($evening,"PO2",$row,$brix);

					  	break;

					  }

					case "EVENING": 

					  { 

					  	addwo($evening,"PO2",$row,$brix);

					  	break;

					  }

				}

			}

			elseif ($pofreq2 > 2)

			{

				addwo($morning,"PO2",$row,$brix);

				addwo($noon,"PO2",$row,$brix);

				addwo($evening,"PO2",$row,$brix);

			}

		}

		if (isyes($pdyesno) & withinrange($brix,$pdstartbrix,$pdendbrix))

		{

			$added=1;

	//		    echo 'adding pd1'.'-'.$timeslot2.'<br>';

			if ($pdfreq == 1)

			{

				switch($timeslot2)

				{

					case "MORNING": addwo($morning,"PD",$row,$brix); break;

					case "NOON": addwo($noon,"PD",$row,$brix); break;

					case "EVENING": addwo($evening,"PD",$row,$brix); break;

					default: addwo($morning,"PD",$row,$brix);

				}

			}

			elseif ($pdfreq == 2)

			{

				switch($timeslot2)

				{

					case "MORNING": 

					  { 

					  	addwo($morning,"PD",$row,$brix);

					  	addwo($evening,"PD",$row,$brix);

					  	break;

					  }

					case "NOON": 

					  { 

					  	addwo($noon,"PD",$row,$brix);

					  	addwo($evening,"PD",$row,$brix);

					  	break;

					  }

					case "EVENING": 

					  { 

					  	addwo($evening,"PD",$row,$brix);

					  	break;

					  }

				}

			}

			elseif ($pdfreq == 3)

			{

				addwo($morning,"PD",$row,$brix);

				addwo($noon, "PD",$row,$brix);

				addwo($evening,"PD",$row,$brix);

			}

		}

		if (isyes($pdyesno2) & withinrange($brix,$pdstartbrix2,$pdendbrix2))

		{

			$added=1;

			      //   echo 'adding pd2'.'-'.$timeslot3.'<br>';

	//		

			if ($pdfreq2 == 1)

				switch($timeslot3)

				{

					case "MORNING": addwo($morning,"PD2",$row,$brix); break;

					case "NOON": addwo($noon,"PD2",$row,$brix); break;

					case "EVENING": addwo($evening,"PD2",$row,$brix); break;

					default: addwo($morning,"PD2",$row,$brix);

				}

			elseif ($pdfreq2 == 2)

			{

				switch($timeslot3)

				{

					case "MORNING": 

					  { 

					  	addwo($morning,"PD2",$row,$brix);

					  	addwo($evening,"PD2",$row,$brix);

					  	break;

					  }

					case "NOON": 

					  { 

					  	addwo($noon,"PD2",$row,$brix);

					  	addwo($evening,"PD2",$row,$brix);

					  	break;

					  }

					case "EVENING": 

					  { 

					  	addwo($evening,"PD2",$row,$brix);

					  	break;

					  }

				}

			}

			elseif ($pdfreq2 == 3)

			{

				addwo($morning,"PD2",$row,$brix);

				addwo($noon, "PD2",$row,$brix);

				addwo($evening,"PD2",$row,$brix);

			}

		}

		if ($added==0)

		{

			//           echo 'adding pd2<br>';

			//  addwo($morning,"DRYICE",$row);

		}

		$collection->nextitem();

	}

	// echo $thedate;

//	echo '<pre>';

//	print_r($morning);

//	exit;

	

	switch ($timeslotgen)

	{

		case "MORNING":	addwo2db("MORNING",$morning, $thedate); break;

	    case "NOON": 

	    {

	//    	echo '<pre>';

	//    	print_r($noon);

	    	 addwo2db("NOON",$noon, $thedate);

	    	 break;

	    }

        case "EVENING" : addwo2db("EVENING",$evening, $thedate); break;

 	}

}

   ?>