<?php

session_start();

?>

<html>



<head>

  <title></title>

   <script type="text/javascript" src="popup/overlibmws.js"></script>

   <script type="text/javascript" src="popup/overlibmws_draggable.js"></script>



</head>



<body>

<link rel="stylesheet" type="text/css" href="../site.css">

 <div id="overDiv" style="position:absolute; visibility:hidden; z-index:1000"></div> 



<?php



include ("startdb.php");

include ("displayqueryresult.php");

include ("buildpopdsheet2.php");

include ("queryupdatefunctions.php");





if ($datefilter=="")

{

   $_SESSION['datefilter']= date("Y-m-d");

}

$datefilter=$_SESSION['datefilter'];



if ($statusfilter=="")

{

   session_register('statusfilter');

   $statusfilter="ASSIGNED";

}

if ($showpopd=="")

{

  session_register('showpopd');

  $showpopd="PO";

}





if (isset($_GET['showtimeslot'])) $showtimeslot=$_GET['showtimeslot'];

if (isset($_GET['showpopd'])) $showpopd=$_GET['showpopd'];



function displaysignoff($result,$popd,$morning)

{



  $num_results = mysql_num_rows($result);



  echo '<table align="center" border="1">';

  echo '<tr>';

  if ($popd=="PO")

    if ($morning)

      echo '<td align=right><table border="1"><td>DEL</td><td align="center" colspan="2">MOVE</td><td align="center" >SWP</td><td align="center" colspan="2">CPY</td></table></td><td align="center">LOT</td><td align="center">VESSEL<br>TYPE</td><td align="center">VESSEL<br>ID</td><td>DURATION</td><td>ADDS</td><td>EXTRAS</td><td>BRIX</td><td>TEMP</td><td>INIT</td>';

    else

      echo '<td align=right><table border="1"><td>DEL</td><td align="center" colspan="2">MOVE</td><td align="center" >SWP</td><td align="center" colspan="2">CPY</td></table></td><td align="center">LOT</td><td align="center">VESSEL<br>TYPE</td><td align="center">VESSEL<br>ID</td><td>DURATION</td><td>ADDS</td><td>EXTRAS</td><td>INIT</td>';

  if ($popd=="PD")

    if ($morning)

      echo '<td align=right><table border="1"><td>DEL</td><td align="center" colspan="2">MOVE</td><td align="center" >SWP</td><td align="center" colspan="2">CPY</td></table></td><td>LOT</td><td align="center">VESSEL<br>TYPE</td><td align="center">VESSEL<br>ID</td><td>STRENGTH</td><td>ADDS</td><td>EXTRAS</td><td>BRIX</td><td>TEMP</td><td>INIT</td>';

    else

      echo '<td align=right><table border="1"><td>DEL</td><td align="center" colspan="2">MOVE</td><td align="center" >SWP</td><td align="center" colspan="2">CPY</td></table></td><td>LOT</td><td align="center">VESSEL<br>TYPE</td><td align="center">VESSEL<br>ID</td><td>STRENGTH</td><td>ADDS</td><td>EXTRAS</td><td>INIT</td>';

  if ($popd=="DRYICE")

    if ($morning)

      echo '<td align=right><table border="1"><td>DEL</td><td align="center" colspan="2">MOVE</td><td align="center" >SWP</td><td align="center" colspan="2">CPY</td></table></td><td>LOT</td><td align="center">VESSEL<br>TYPE</td><td align="center">VESSEL<br>ID</td><td>INIT</td>';



  echo '</tr>';



  for ($i=0; $i<$num_results; $i++)

  {

    echo '<tr>';



     $row = mysql_fetch_array($result);

      $bt = getbrixtemp($row['LOT'],$row['VESSELTYPE'],$row['VESSELID'],$row['DUEDATE']);

     

     $wo = getwo($row['ID']);



     if ($row['RELATEDADDITIONSID']>0)

       $additions="YES";

     else

       $additions="";



     $postparameters='?woid='.$row['ID'].'&lot='.$row['LOT'].'&vesseltype='.$row['VESSELTYPE'].'&vessel='.

           $row['VESSELID'].'&date='.$row['DUEDATE'];

      



     echo '<td align="center">';

     echo '<table align="center" border="0">';

     echo '<td align=center width=10 style="border-style: solid; border-color: Sienna; border-width: 1">'.($i+1).'</td>';

     if ($row['AUTOGENERATED']=="YES") echo '<td width=10>A</td>';

     else echo '<td width=10></td>';

       echo '<td align=center width=40>'.$wo['workperformedby'].'</td>';

     echo '<td align="center"> <a href=dailypopdsheet.php?action=del&woid='.$row['ID'].'><img border="0" src="../images/tick.gif" width="9" height="9"></a></td><td></td>';

     echo '<td><a href=dailypopdsheet.php?action=down&woid='.$row['ID'].'><img border="0" src="../images/arrowdown.GIF" width="14" height="10"></a></td>';

     echo '<td> <a href=dailypopdsheet.php?action=up&woid='.$row['ID'].'><img border="0" src="../images/arrowup.GIF" width="14" height="10"></a></td>';

     if ($popd!="DRYICE") echo '<td> <a href=dailypopdsheet.php?action=swap&woid='.$row['ID'].'><img border="0" src="../images/blue.gif" width="9" height="9"></a></td>';

     echo '<td><a href=dailypopdsheet.php?action=cdown&woid='.$row['ID'].'><img border="0" src="../images/arrowdown.GIF" width="14" height="10"></a></td>';

     echo '<td><a href=dailypopdsheet.php?action=cup&woid='.$row['ID'].'><img border="0" src="../images/arrowup.GIF" width="14" height="10"></a></td>';

     echo '<td><a href=dailypopdsheet.php?action=cnextday&woid='.$row['ID'].'><img border="0" src="../images/arrowright.GIF" width="10" height="14"></a></td>';

     echo '</table>';

     echo '</td>';

     echo '<form method="POST" action="dailypopdsheet.php'.$postparameters.'&action=mod">';

     echo '<td align="center"><a href=viewfermcurves.php'.$postparameters .'&

              allowadd=TRUE onmouseover="return overlib(\''.$bt[brix].'\',WIDTH, 50);" onmouseout="nd();">'.$row['LOT'].'</a></td>';

//    echo '<td align="center"><a href=viewfermcurves.php'.$postparameters .'&allowadd=TRUE>'.$row['LOT'].'</a></td>';

 //   echo '<td align="center"><a href=fermprot.php'.$postparameters.'>'.$row['LOT'].'</a></td>';

     echo '<td align="center"> '.$row['VESSELTYPE'].'</td>';

     echo '<td align="center">'.$row['VESSELID'].'</td>';

     if ($popd=="PO")

             echo '<td align="center"><input type="text" size="3" height="10" name="duration" value="'.$row['DURATION'].'"></td>';

     if ($popd=="PD")

             echo '<td align="center"><input type="text" size="7" height="10" name="strength" value="'.$row['STRENGTH'].'"></td>';

     if ($popd!="DRYICE") echo '<td align="center">'.$additions.'</td>';

     if ($popd!="DRYICE") echo '<td align="center"><input type="text" name="alert" height="10" size="6" value="'.$row['ALERT'].'"></td>';





     if ($morning)

     {

        if ($popd!="DRYICE") echo '<td align="center"><input type="text" name="brix" height="10" size="3" value="'.$bt['brix'].'"></td>';

        if ($popd!="DRYICE") echo '<td align="center"><input type="text" name="temp" height="10" size="3" value="'.$bt['temp'].'"</td>';

     }

     echo '<td align="center"><input type="text" name="init" height="10" size="3" value="'.$row['COMPLETEBY'].'"</td>';

     echo '<td align="center"><input type="image" src="../images/5push.gif" width="14" height="10"></td>';

     echo '</form>';

     echo '</tr>';



  }

  echo '</table>';



}





if ($_GET['action']=="setfilters")

{

    $datefilter=$_POST['date'];

    $statusfilter=$_POST['status'];

}



if ($_GET['action']=="addrec")

{

    addpopdwo($_POST['LOTVESSEL'],

       $_POST['DATE'],

       $_POST['TYPE'],

       $_POST['TIMESLOT'],

       $_POST['STRENGTH'],

       $_POST['PODURATION'],

       $_POST['ALERT']);

}



if ($_GET['setfilterdate']=="yesterday")

{

    $datefilter=date("Y-m-d",strtotime($datefilter)-86400);

}



if ($_GET['setfilterdate']=="tomorrow")

{

    $datefilter=date("Y-m-d",strtotime($datefilter)+86400);

}

if ($_GET['action']=="del")

{

    deletewo($_GET['woid']);

}



if ($_GET['action']=="swap")

{

    swappopd($_GET['woid']);

}

if ($_GET['action']=="cnextday")

{

    copynextday($_GET['woid']);

}

if (($_GET['action']=="down" | $_GET['action']=="up"))

{

    downuppopd($_GET['action'],$_GET['woid']);

}

 if (($_GET['action']=="cdown" | $_GET['action']=="cup"))

{

    copydownuppopd($_GET['action'],$_GET['woid']);

}



if ($_GET['action']=="mod")

{

   if ($_POST['temp']<45)

      $thetemp=$_POST['temp']*9/5+32;

   else

      $thetemp=$_POST['temp'];

   updatepopdwo($_GET['woid'],$_GET['lot'],$_GET['vesseltype'],$_GET['vessel'],$_GET['date'],$_POST['brix'],$thetemp,$_POST['strength'],$_POST['duration'],$_POST['init'],$_POST['alert']);



}



$querymorningpd='SELECT `wo`.`RELATEDADDITIONSID`, `wo`.`AUTOGENERATED`,`wo`.`ALERT`,`wo`.`ID`, `wo`.`COMPLETEBY`, `wo`.`STATUS`,`wo`.`DUEDATE`,`wo`.`LOT`,`wo`.`VESSELTYPE`,`wo`.`VESSELID`,`wo`.`STRENGTH`

   FROM `wo`

   WHERE (`wo`.`TIMESLOT`= "MORNING" AND wo.STATUS="'.$statusfilter.'" AND DATE_FORMAT(wo.DUEDATE,"%Y-%m-%d")="'.$datefilter.'" AND `wo`.`TYPE`= "PUNCH DOWN" and wo.DELETED=0)

   ORDER BY wo.CLIENTCODE, wo.BRIX DESC, `wo`.`DUEDATE`,`wo`.`LOT` DESC,`wo`.`VESSELTYPE`,`wo`.`VESSELID`,`wo`.`TIMESLOT`';



$querymorningpo='SELECT `wo`.`RELATEDADDITIONSID`, `wo`.`AUTOGENERATED`,`wo`.`ALERT`, `wo`.`ID`, `wo`.`COMPLETEBY`, `wo`.`STATUS`,`wo`.`DUEDATE`,`wo`.`LOT`,`wo`.`VESSELTYPE`,`wo`.`VESSELID`,`wo`.`DURATION`

   FROM `wo`

   WHERE (`wo`.`TIMESLOT`= "MORNING" AND wo.STATUS="'.$statusfilter.'" AND DATE_FORMAT(wo.DUEDATE,"%Y-%m-%d")="'.$datefilter.'" AND `wo`.`TYPE`= "PUMP OVER" and wo.DELETED=0)

   ORDER BY wo.CLIENTCODE, wo.BRIX DESC, `wo`.`LOT`,`wo`.`VESSELTYPE`,`wo`.`VESSELID`,`wo`.`TIMESLOT`';



$querynoonpd='SELECT `wo`.`RELATEDADDITIONSID`, `wo`.`AUTOGENERATED`,`wo`.`ALERT`,`wo`.`ID`, `wo`.`COMPLETEBY`, `wo`.`STATUS`,`wo`.`DUEDATE`,`wo`.`LOT`,`wo`.`VESSELTYPE`,`wo`.`VESSELID`,`wo`.`STRENGTH`

   FROM `wo`

   WHERE (`wo`.`TIMESLOT`= "NOON" AND wo.STATUS="'.$statusfilter.'" AND DATE_FORMAT(wo.DUEDATE,"%Y-%m-%d")="'.$datefilter.'" AND `wo`.`TYPE`= "PUNCH DOWN" and wo.DELETED=0)

   ORDER BY wo.CLIENTCODE, wo.BRIX DESC, `wo`.`DUEDATE`,`wo`.`LOT` DESC,`wo`.`VESSELTYPE`,`wo`.`VESSELID`,`wo`.`TIMESLOT`';



$querynoonpo='SELECT `wo`.`RELATEDADDITIONSID`, `wo`.`AUTOGENERATED`,`wo`.`ALERT`,`wo`.`ID`, `wo`.`COMPLETEBY`, `wo`.`STATUS`,`wo`.`DUEDATE`,`wo`.`LOT`,`wo`.`VESSELTYPE`,`wo`.`VESSELID`,`wo`.`DURATION`

   FROM `wo`

   WHERE (`wo`.`TIMESLOT`= "NOON" AND wo.STATUS="'.$statusfilter.'" AND DATE_FORMAT(wo.DUEDATE,"%Y-%m-%d")="'.$datefilter.'" AND `wo`.`TYPE`= "PUMP OVER" and wo.DELETED=0)

   ORDER BY wo.CLIENTCODE, wo.BRIX DESC, `wo`.`DUEDATE`,`wo`.`LOT` DESC,`wo`.`VESSELTYPE`,`wo`.`VESSELID`,`wo`.`TIMESLOT`';



$queryeveningpd='SELECT `wo`.`RELATEDADDITIONSID`, `wo`.`AUTOGENERATED`,`wo`.`ALERT`,`wo`.`ID`, `wo`.`COMPLETEBY`, `wo`.`STATUS`,`wo`.`DUEDATE`,`wo`.`LOT`,`wo`.`VESSELTYPE`,`wo`.`VESSELID`,`wo`.`STRENGTH`

   FROM `wo`

   WHERE (`wo`.`TIMESLOT`= "EVENING" AND wo.STATUS="'.$statusfilter.'" AND DATE_FORMAT(wo.DUEDATE,"%Y-%m-%d")="'.$datefilter.'" AND `wo`.`TYPE`= "PUNCH DOWN" and wo.DELETED=0)

   ORDER BY wo.CLIENTCODE, wo.BRIX DESC, `wo`.`DUEDATE`,`wo`.`LOT` DESC,`wo`.`VESSELTYPE`,`wo`.`VESSELID`,`wo`.`TIMESLOT`';



$queryeveningpo='SELECT `wo`.`RELATEDADDITIONSID`, `wo`.`AUTOGENERATED`,`wo`.`ALERT`,`wo`.`ID`, `wo`.`COMPLETEBY`, `wo`.`STATUS`,`wo`.`DUEDATE`,`wo`.`LOT`,`wo`.`VESSELTYPE`,`wo`.`VESSELID`,`wo`.`DURATION`

   FROM `wo`

   WHERE (`wo`.`TIMESLOT`= "EVENING" AND wo.STATUS="'.$statusfilter.'" AND DATE_FORMAT(wo.DUEDATE,"%Y-%m-%d")="'.$datefilter.'" AND `wo`.`TYPE`= "PUMP OVER" and wo.DELETED=0)

   ORDER BY wo.CLIENTCODE, wo.BRIX DESC, `wo`.`DUEDATE`,`wo`.`LOT` DESC,`wo`.`VESSELTYPE`,`wo`.`VESSELID`,`wo`.`TIMESLOT`';



$querymorningdryice='SELECT `wo`.`RELATEDADDITIONSID`, `wo`.`AUTOGENERATED`,`wo`.`ALERT`,`wo`.`ID`, `wo`.`COMPLETEBY`, `wo`.`STATUS`,`wo`.`DUEDATE`,`wo`.`LOT`,`wo`.`VESSELTYPE`,`wo`.`VESSELID`,`wo`.`DURATION`

   FROM `wo`

   WHERE (`wo`.`TIMESLOT`= "MORNING" AND wo.STATUS="'.$statusfilter.'" AND DATE_FORMAT(wo.DUEDATE,"%Y-%m-%d")="'.$datefilter.'" AND `wo`.`TYPE`= "DRYICE" and wo.DELETED=0)

   ORDER BY wo.CLIENTCODE, `wo`.`DUEDATE`,`wo`.`LOT` DESC,`wo`.`VESSELTYPE`,`wo`.`VESSELID`,`wo`.`TIMESLOT`';



//   echo $querymorningdryice;

  if ($_GET['action']=="regenerate") 

  {

  	buildpopdsheet($datefilter, $_GET['timeslotgen']);

  }

  if ($_GET['action']=="clear") deleteautogenerated($datefilter, $_GET['timeslotgen']);



  echo '<form method="POST" action="dailypopdsheet.php?action=setfilters">';

  echo '<table width="100%" border="1"><tr><td align="center" colspan="5">PUMP OVER / PUNCH DOWN SHEET</td></tr>';

  echo '<tr><td align="center">'.date("l",strtotime($datefilter)).'<br><a href=dailypopdsheet.php?setfilterdate=yesterday><--  </a>

       <input type="text" name="date" size="12" value='.$datefilter.'>

       <a href=dailypopdsheet.php?setfilterdate=tomorrow>  --></a></td>';

//        echo '<td align="center"><input type="text" name="status" size="15" value='.$statusfilter.'></td>';

        echo '<td align="center">'.DrawComboFromEnum("wo","STATUS",$statusfilter,"status").'</td>';

        echo '<td align="center"><input type="submit" name="B1" value="FILTER"></td></form>';

        echo '<td align="center"><table border="1"><tr><td align="center" width="50%"><a href="excel/genexcel.php">GENERATE EXCEL</a></td><td align="center" width="50%"><a href=dailypopdsheet.php?action=clear?timeslot=NOON>CLEAR AUTOGENERATED</a></td></tr>';

        echo '<tr><td align="center"><a href=staff.php>STAFF HOME</a></td><td align="center"><a href=dailypopdsheet.php?action=regenerate&timeslotgen=MORNING>REGENERATE MORNING</a><br><a href=dailypopdsheet.php?action=regenerate&timeslotgen=NOON>REGENERATE NOON</a><br><a href=dailypopdsheet.php?action=regenerate&timeslotgen=EVENING>REGENERATE EVENING</a></td></tr>';

        echo '</table></td>';

  echo '</tr></table>';

  echo '<table width="100%" border="1"><tr><td align="center">';

  if ($showpopd=="PO")

    {

       echo '<b><u>MORNING PUMP OVERS</b></u><a href=addsinglepopd.php?type=PO&date='.$datefilter.'&timeslot=MORNING>  (ADD)</a><br><br>';

       echo '<a href=dailypopdsheet.php?showpopd=DRYICE>DRY ICE ONLY   </a><a href=dailypopdsheet.php?showpopd=PD&date='.$datefilter.'&timeslot=MORNING>PUNCH DOWN</a></td></tr>';

       displaysignoff(mysql_query($querymorningpo),"PO",TRUE);

    }

    else

  if ($showpopd=="PD")

  {

       echo '<b><u>MORNING PUNCH DOWNS</b></u><a href=addsinglepopd.php?type=PD&date='.$datefilter.'&timeslot=MORNING>  (ADD)</a><br><br>';

    echo '<a href=dailypopdsheet.php?showpopd=DRYICE>DRY ICE ONLY   </a><a href=dailypopdsheet.php?showpopd=PO&date='.$datefilter.'&timeslot=MORNING>PUMP OVERS</a></td></tr>';

    displaysignoff(mysql_query($querymorningpd),"PD",TRUE);

  }

  if ($showpopd=="DRYICE")

  {

    echo '<b><u>MORNING DRY ICE ONLY</b></u><a href=addsinglepopd.php?type=DI&date='.$datefilter.'&timeslot=MORNING>  (ADD)</a><br><br>';

    echo '<a href=dailypopdsheet.php?showpopd=PO>  PUMP OVERS   </a><a href=dailypopdsheet.php?showpopd=PD&date='.$datefilter.'&timeslot=MORNING>  PUNCH DOWN   </a></td></tr>';

    displaysignoff(mysql_query($querymorningdryice),"DRYICE",TRUE);

  }

  echo '</table>';



  echo '<table width="100%" border="1"><tr><td align="center"><br><br>';

  if ($showpopd=="PO")

    {

       echo '<b><u>NOON PUMP OVERS</b></u><a href=addsinglepopd.php?type=PO&date='.$datefilter.'&timeslot=NOON>  (ADD)</a><br><br></td></tr>';

//       echo '<a href=dailypopdsheet.php?showpopd=PD>PUNCH DOWN</a>   PUMP OVERS  <a href=addsinglepopd.php?type=PO>(ADD)</td></tr>';

       displaysignoff(mysql_query($querynoonpo),"PO",FALSE);

    }

  else

  {

       echo '<b><u>NOON PUNCH DOWNS</b></u><a href=addsinglepopd.php?type=PD&date='.$datefilter.'&timeslot=NOON>  (ADD)</a><br><br></td></tr>';

//  echo '<a href=dailypopdsheet.php?showpopd=PO>PUMP OVERS</a>   PUNCH DOWNS  <a href=addsinglepopd.php?type=PD>(ADD)</td></tr>';

    displaysignoff(mysql_query($querynoonpd),"PD",FALSE);

  }

  echo '</table>';



  echo '<table width="100%" border="1"><tr><td align=center><br>';

   if ($showpopd=="PO")

    {

       echo '<b><u>EVENING PUMP OVERS</b></u><a href=addsinglepopd.php?type=PO&date='.$datefilter.'&timeslot=EVENING>  (ADD)</a><br><br></td></tr>';

//       echo '<a href=dailypopdsheet.php?showpopd=PD>PUNCH DOWN</a>   PUMP OVERS  <a href=addsinglepopd.php?type=PO>(ADD)</td></tr>';

       displaysignoff(mysql_query($queryeveningpo),"PO",FALSE);

    }

  else

  {

         echo '<b><u>EVENING PUNCH DOWNS</b></u><a href=addsinglepopd.php?type=PD&date='.$datefilter.'&timeslot=EVENING>  (ADD)</a><br><br></td></tr>';

//  echo '<a href=dailypopdsheet.php?showpopd=PO>PUMP OVERS</a>   PUNCH DOWNS  <a href=addsinglepopd.php?type=PD>(ADD)</td></tr>';

    displaysignoff(mysql_query($queryeveningpd),"PD",FALSE);

  }

  echo '</table>';







  ?>



</body>



</html>

