<?php

  session_start();

?>

<html>



<head>

  <title></title>

  <link rel="stylesheet" type="text/css" href="../site.css">

    <script type="text/javascript" src="../jscalendar/calendar.js"></script>

  <script type="text/javascript" src="../jscalendar/lang/calendar-en.js"></script>

  <script type="text/javascript" src="../jscalendar/calendar-setup.js"></script>

  <script language="JavaScript" src="../tigra_tables/tigra_tables.js"></script>



</head>



<body>



<?php



   include ("startdb.php");

   include ("queryupdatefunctions.php");

   include ("lotinforecords.php");



function doquery($thedate,$value)

{

         $query='INSERT INTO wo SET

        wo.TYPE="'.$_POST['activity'].'",

       wo.DUEDATE="'.datetimestr($thedate,'MORNING','START').'",

        wo.ENDDATE="'.datetimestr($thedate,'MORNING','END').'",

        wo.LOT="'.$value.'",

        wo.REQUESTOR="'.$_SESSION['requestor'].'",

        wo.DELETED=0,

        wo.OTHERDESC="'.$_POST['comments'].'",

        wo.WORKPERFORMEDBY="'.$_POST['workperformedby'].'",

        wo.AUTOGENERATED="NO",

        wo.CREATIONDATE="'.date("Y-m-d").'",

        wo.CLIENTCODE="'.$_SESSION['clientcode'].'"';

        //echo $query.'<br>';

        mysql_query($query);

        echo 'Added '.$_POST['activity'].' work order to '.$value.' for date '.$thedate.'<br>';



}

function datetimestr($date,$slot,$startperiod)

{

    $dt=date("Y-m-d",strtotime($date));

    switch ($slot)

    {

        case "MORNING":

        {

            if ($startperiod=="START")

            {

                $dt=$dt.' 06:00:00';

            }

            else

            {

                $dt=$dt.' 12:00:00';

            }

            break;

        }

        case "NOON":

        {

            if ($startperiod=="START")

            {

                $dt=$dt.' 12:00:00';

            }

            else

            {

                $dt=$dt.' 16:00:00';

            }

            break;

        }

        case "EVENING":

        {

            if ($startperiod=="START")

            {

                $dt=$dt.' 16:00:00';

            }

            else

            {

                $dt=$dt.' 21:00:00';

            }

            break;

        }

    }

    return $dt;

}

  $clientcode=$_SESSION['clientcode'];



  if ($_GET['returnpage']!="")

  {

     $_SESSION['returnpage']=$_GET['returnpage'];

  //   echo 'setting returnpage';

    }



  $date=$_GET['todate'];

  $totalgallons=0;

  $query='SELECT * FROM  `lots` WHERE (`lots`.`CLIENTCODE` = "'.clientid($clientcode).'" AND 

           lots.YEAR="'.$_SESSION['vintage'].'") ORDER BY lots.LOTNUMBER';

//  echo $query;

  $result=mysql_query($query);

  $num_rows=mysql_num_rows($result);



  if ($_GET['action']=="mod")

  {

    foreach ($_POST as $key=>$value)

    {

      $iteration_count=0;

        if (substr($key,0,3)=="lot")

        {

          $m=date("m",strtotime($_POST['dateofwork']));

          $d=date("d",strtotime($_POST['dateofwork']));

          $y=date("Y",strtotime($_POST['dateofwork']));



         switch ($_POST['FREQUENCY'])

         {

           case ("ONCE_EVERY_4_WEEKS"):

           {

               while ($iteration_count<$_POST['ITERATIONS'])

               {

                 $iteration_count++;

                 $thedateofwork=date("m/d/Y",mktime(0,0,0,$m,$d,$y));

                 doquery($thedateofwork,$value);

                 $d=$d+28;

               }

               break;

           }

           case ("ONCE_A_WEEK"):

           {

               while ($iteration_count<$_POST['ITERATIONS'])

               {

                 $iteration_count++;

                 $thedateofwork=date("m/d/Y",mktime(0,0,0,$m,$d,$y));

                 doquery($thedateofwork,$value);

                 $d=$d+7;

               }

               break;

           }

           case ("ONCE_EVERY_2_WEEKS"):

           {

               while ($iteration_count<$_POST['ITERATIONS'])

               {

                 $iteration_count++;

                 $thedateofwork=date("m/d/Y",mktime(0,0,0,$m,$d,$y));

                 doquery($thedateofwork,$value);

                 $d=$d+14;

               }

           }

         }

        }



    }

  }

  

  echo '<form  name=main method="POST" action="'.$PHP_SELF.'?action=mod">';



  echo '<table border=1 width 1000 align=center>';

  echo '<tr><td align=center width=650>';

  echo '<table border="1" width=100% align="center">';

  for ($i=0;$i<$num_rows;$i++)

  {

    $row=mysql_fetch_array($result);

    echo '<tr>';

    echo '<td>';

    echo '<input type=checkbox value='.$row['LOTNUMBER'].' name=lot_'.$row['LOTNUMBER'].'>';

    echo '</td>';

    echo '<td align="center">';

    echo '<a href=showlotinfo.php?lot='.$row['LOTNUMBER'].'>'.$row['LOTNUMBER'].'</a></td><td align=left>'.$row['DESCRIPTION'];

    echo '</td>';

    if ($_GET['showgallons']=="YES")

    {

        $li=lotinforecords($row['LOTNUMBER']);

        $li=$li[count($li)-1];

        $gallons=$li['ending_tankgallons'];

        $cases=$gallons/2.3775;

        $totalgallons+=$gallons;

        echo '<td align="right">'.number_format($gallons,2).'</td>';

        echo '<td align="right">'.number_format($cases,0).'</td>';

    }

    echo '</tr>';

  }

  echo '</table>';

  echo '</td>';

//--------------------

  echo '<td valign=top>';

  echo '<table align=center width=100%>';

  echo '<tr>';

  echo '<td align=center>';

    echo '<tr><td width=45% align=left>START DATE:';

    echo '</td><td>';

    echo '<input type="text" name="dateofwork" size="12" value="'.date("m/d/Y",strtotime($dateofwork)).'">';

    echo '<button id="trigger">...</button>';

    echo '</td></tr>';

    echo '<tr><td>';

    echo 'WO TYPE: ';

    echo '</td><td>';

    echo DrawComboFromEnum("wo","TYPE", "TOPPING","activity");

    echo '</td></tr>';

    echo '<tr><td>';

    $thefreq=array('EVERYDAY'=>1,'ONCE_A_WEEK'=>1,'ONCE_EVERY_2_WEEKS'=>1,'ONCE_EVERY_4_WEEKS'=>1);

    echo 'FREQUENCY: ';

    echo '</td><td>';

    echo DrawComboFromArray($thefreq,"ONCE_EVERY_2_WEEKS","FREQUENCY");

    echo '</td></tr>';



    echo '<tr><td>';

    $iterations=array(1=>1,1,1,1,1);

    echo 'NUMBER OF ITERATIONS: ';

    echo '</td><td>';

    echo DrawComboFromArray($iterations,"3","ITERATIONS");

    echo '</td></tr>';

    echo '<tr><td colspan=2>';

echo 'COMMENTS: <textarea rows="5" cols="60" name="comments">'.$_SESSION['desc'].'</textarea></td></tr>';



    echo '<tr><td>';

echo 'WORK PERFORMED BY: ';

    echo '</td><td>';

    echo DrawComboFromEnum("wo","WORKPERFORMEDBY", "CCC","workperformedby");

echo '</td></tr>';



echo '<tr><td><input type="submit" value="DOIT" name="B1">';

echo '</td></tr>';





//--------------------

  echo '</td>';

  echo '</tr>';

  echo '</table>';

  echo '</form>';

?>



</body>



</html>

